import { useState, useMemo } from "react";
import ToolTip from "../components/reusable/HelpCircle";

const DCF = () => {
  const [formData, setFormData] = useState({
    initialFCF: "",
    growthRate: "",
    terminalGrowthRate: "",
    discountRate: "",
    projectionYears: "5",
  });

  const [showResults, setShowResults] = useState(false);

  const handleInputChange = (field, value) => {
    setFormData((prev) => ({
      ...prev,
      [field]: value,
    }));
  };

  const handleCalculate = () => {
    if (Object.values(formData).every((val) => val !== "")) {
      setShowResults(true);
    }
  };

  const dcfResults = useMemo(() => {
    if (!showResults || Object.values(formData).some((val) => val === "")) {
      return null;
    }

    const initialFCF = parseFloat(formData.initialFCF);
    const growthRate = parseFloat(formData.growthRate) / 100;
    const terminalGrowthRate = parseFloat(formData.terminalGrowthRate) / 100;
    const discountRate = parseFloat(formData.discountRate) / 100;
    const years = parseInt(formData.projectionYears);

    // Calculate projected FCFs
    const projectedFCFs = [];
    for (let i = 1; i <= years; i++) {
      const fcf = initialFCF * Math.pow(1 + growthRate, i);
      projectedFCFs.push(fcf);
    }

    // Calculate present values
    const presentValues = projectedFCFs.map((fcf, index) => {
      return fcf / Math.pow(1 + discountRate, index + 1);
    });

    // Calculate terminal value
    const terminalFCF = projectedFCFs[years - 1] * (1 + terminalGrowthRate);
    const terminalValue = terminalFCF / (discountRate - terminalGrowthRate);
    const presentValueOfTerminalValue =
      terminalValue / Math.pow(1 + discountRate, years);

    // Calculate enterprise value
    const sumOfPresentValues = presentValues.reduce((sum, pv) => sum + pv, 0);
    const enterpriseValue = sumOfPresentValues + presentValueOfTerminalValue;

    return {
      projectedFCFs,
      presentValues,
      terminalValue,
      presentValueOfTerminalValue,
      enterpriseValue,
      sumOfPresentValues,
    };
  }, [formData, showResults]);

  return (
    <div className="flex flex-col gap-6 max-w-6xl mx-auto p-4">
      <div className="relative h-36 rounded-xl overflow-hidden">
        <img
          src="https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=1400&q=80"
          alt=""
          className="absolute inset-0 w-full h-full object-cover"
        />
        <div className="absolute inset-0 bg-gradient-to-r from-black/75 to-black/30 flex flex-col justify-center px-6 md:px-10">
          <h1 className="text-2xl md:text-3xl font-bold text-white drop-shadow">
            DCF Calculator
          </h1>
          <p className="text-white/90 text-sm md:text-base mt-1">
            Discounted cash flow valuation — all math runs in your browser.
          </p>
        </div>
      </div>

      {/* Input Form */}
      <div className="bg-white dark:bg-neutral-800 rounded-lg shadow-lg p-6">
        <h2 className="text-xl font-semibold dark:text-white mb-4">
          Input Parameters
        </h2>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          <div className="flex items-start gap-1 flex-col">
            <div className="flex items-center gap-2">
              <label
                className="text-base font-medium dark:text-white flex items-center"
                htmlFor="initial-fcf"
              >
                Initial FCF (Rs Cr)
              </label>
              <ToolTip message="The Free Cash Flow (FCF) generated by the company in the most recent fiscal year. This serves as the base value for projecting future cash flows." />
            </div>
            <input
              type="number"
              id="initial-fcf"
              value={formData.initialFCF}
              onChange={(e) => handleInputChange("initialFCF", e.target.value)}
              placeholder="e.g., 500"
              className="w-full border border-neutral-300 rounded-md p-3 dark:bg-neutral-700 dark:border-neutral-600 dark:text-white outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div className="flex items-start gap-1 flex-col">
            <div className="flex items-center gap-2">
              <label
                className="text-base font-medium dark:text-white"
                htmlFor="growth-rate"
              >
                Growth Rate (%)
              </label>
              <ToolTip message="The expected annual growth rate of free cash flow for the projection period. This should reflect the company's growth prospects." />
            </div>
            <input
              type="number"
              id="growth-rate"
              value={formData.growthRate}
              onChange={(e) => handleInputChange("growthRate", e.target.value)}
              placeholder="e.g., 10"
              step="0.1"
              className="w-full border border-neutral-300 rounded-md p-3 dark:bg-neutral-700 dark:border-neutral-600 dark:text-white outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div className="flex items-start gap-1 flex-col">
            <div className="flex items-center gap-2">
              <label
                className="text-base font-medium dark:text-white"
                htmlFor="terminal-growth-rate"
              >
                Terminal Growth Rate (%)
              </label>
              <ToolTip message="The perpetual growth rate beyond the projection period. Usually set equal to or below long-term GDP growth (2-4%)." />
            </div>
            <input
              type="number"
              id="terminal-growth-rate"
              value={formData.terminalGrowthRate}
              onChange={(e) =>
                handleInputChange("terminalGrowthRate", e.target.value)
              }
              placeholder="e.g., 3"
              step="0.1"
              className="w-full border border-neutral-300 rounded-md p-3 dark:bg-neutral-700 dark:border-neutral-600 dark:text-white outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div className="flex items-start gap-1 flex-col">
            <div className="flex items-center gap-2">
              <label
                className="text-base font-medium dark:text-white"
                htmlFor="discount-rate"
              >
                Discount Rate (WACC) (%)
              </label>
              <ToolTip message="The Weighted Average Cost of Capital (WACC). This represents the required rate of return for investors and is used to discount future cash flows to present value." />
            </div>
            <input
              type="number"
              id="discount-rate"
              value={formData.discountRate}
              onChange={(e) =>
                handleInputChange("discountRate", e.target.value)
              }
              placeholder="e.g., 12"
              step="0.1"
              className="w-full border border-neutral-300 rounded-md p-3 dark:bg-neutral-700 dark:border-neutral-600 dark:text-white outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          <div className="flex items-start gap-1 flex-col">
            <div className="flex items-center gap-2">
              <label
                className="text-base font-medium dark:text-white"
                htmlFor="projection-years"
              >
                Projection Years
              </label>
              <ToolTip message="The number of years to project cash flows explicitly. Typically 5-10 years." />
            </div>
            <select
              id="projection-years"
              value={formData.projectionYears}
              onChange={(e) =>
                handleInputChange("projectionYears", e.target.value)
              }
              className="w-full border border-neutral-300 rounded-md p-3 dark:bg-neutral-700 dark:border-neutral-600 dark:text-white outline-none focus:ring-2 focus:ring-blue-500"
            >
              {[3, 4, 5, 6, 7, 8, 9, 10].map((year) => (
                <option key={year} value={year}>
                  {year} years
                </option>
              ))}
            </select>
          </div>
        </div>

        <button
          onClick={handleCalculate}
          disabled={Object.values(formData).some((val) => val === "")}
          className="mt-6 bg-black/100 disabled:bg-black/40 disabled:cursor-not-allowed text-white font-semibold py-3 px-8 rounded-lg transition duration-200 w-full md:w-auto"
        >
          Calculate DCF Valuation
        </button>
      </div>

      {/* Results Section */}
      {showResults && dcfResults && (
        <div className="bg-white dark:bg-black/40 rounded-lg shadow-lg p-6">
          <h2 className="text-xl font-semibold dark:text-white mb-4">
            DCF Valuation Results
          </h2>

          {/* Summary Cards */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
            <div className="bg-blue-50 dark:bg-black/20 rounded-lg p-4">
              <h3 className="text-sm font-medium text-blue-600 dark:text-blue-400 mb-1">
                Enterprise Value
              </h3>
              <p className="text-2xl font-bold dark:text-white">
                ₹{dcfResults.enterpriseValue.toFixed(2)} Cr
              </p>
            </div>
            <div className="bg-green-50 dark:bg-black/20 rounded-lg p-4">
              <h3 className="text-sm font-medium text-green-600 dark:text-green-400 mb-1">
                PV of Cash Flows
              </h3>
              <p className="text-2xl font-bold dark:text-white">
                ₹{dcfResults.sumOfPresentValues.toFixed(2)} Cr
              </p>
            </div>
            <div className="bg-purple-50 dark:bg-black/20 rounded-lg p-4">
              <h3 className="text-sm font-medium text-purple-600 dark:text-purple-400 mb-1">
                PV of Terminal Value
              </h3>
              <p className="text-2xl font-bold dark:text-white">
                ₹{dcfResults.presentValueOfTerminalValue.toFixed(2)} Cr
              </p>
            </div>
          </div>

          {/* Detailed Projections Table */}
          <div className="overflow-x-auto">
            <table className="w-full border-collapse border border-gray-300 dark:border-gray-900">
              <thead>
                <tr className="bg-gray-50 dark:bg-black">
                  <th className="border border-gray-300 dark:border-gray-900 px-4 py-2 text-left dark:text-white">
                    Year
                  </th>
                  <th className="border border-gray-300 dark:border-gray-900 px-4 py-2 text-left dark:text-white">
                    Projected FCF (₹ Cr)
                  </th>
                  <th className="border border-gray-300 dark:border-gray-900 px-4 py-2 text-left dark:text-white">
                    Present Value (₹ Cr)
                  </th>
                  <th className="border border-gray-300 dark:border-gray-900 px-4 py-2 text-left dark:text-white">
                    Discount Factor
                  </th>
                </tr>
              </thead>
              <tbody>
                {dcfResults.projectedFCFs.map((fcf, index) => {
                  const discountFactor =
                    1 /
                    Math.pow(
                      1 + parseFloat(formData.discountRate) / 100,
                      index + 1
                    );
                  return (
                    <tr
                      key={index}
                      className="hover:bg-gray-50 dark:hover:bg-black/50"
                    >
                      <td className="border border-gray-300 dark:border-gray-900 px-4 py-2 dark:text-white">
                        Year {index + 1}
                      </td>
                      <td className="border border-gray-300 dark:border-gray-900 px-4 py-2 dark:text-white">
                        {fcf.toFixed(2)}
                      </td>
                      <td className="border border-gray-300 dark:border-gray-900 px-4 py-2 dark:text-white">
                        {dcfResults.presentValues[index].toFixed(2)}
                      </td>
                      <td className="border border-gray-300 dark:border-gray-900 px-4 py-2 dark:text-white">
                        {discountFactor.toFixed(4)}
                      </td>
                    </tr>
                  );
                })}
                <tr className="bg-yellow-50 dark:bg-black/20 font-semibold">
                  <td className="border border-gray-300 dark:border-gray-900 px-4 py-2 dark:text-white">
                    Terminal Value
                  </td>
                  <td className="border border-gray-300 dark:border-gray-900 px-4 py-2 dark:text-white">
                    {dcfResults.terminalValue.toFixed(2)}
                  </td>
                  <td className="border border-gray-300 dark:border-gray-900 px-4 py-2 dark:text-white">
                    {dcfResults.presentValueOfTerminalValue.toFixed(2)}
                  </td>
                  <td className="border border-gray-300 dark:border-gray-900 px-4 py-2 dark:text-white">
                    {(
                      1 /
                      Math.pow(
                        1 + parseFloat(formData.discountRate) / 100,
                        parseInt(formData.projectionYears)
                      )
                    ).toFixed(4)}
                  </td>
                </tr>
              </tbody>
              <tfoot>
                <tr className="bg-blue-50 dark:bg-black/30 font-bold">
                  <td className="border border-gray-300 dark:border-gray-900 px-4 py-2 dark:text-white">
                    Total Enterprise Value
                  </td>
                  <td className="border border-gray-300 dark:border-gray-900 px-4 py-2 dark:text-white">
                    -
                  </td>
                  <td className="border border-gray-300 dark:border-gray-900 px-4 py-2 dark:text-white">
                    ₹{dcfResults.enterpriseValue.toFixed(2)} Cr
                  </td>
                  <td className="border border-gray-300 dark:border-gray-900 px-4 py-2 dark:text-white">
                    -
                  </td>
                </tr>
              </tfoot>
            </table>
          </div>

          {/* Assumptions Summary */}
          <div className="mt-6 bg-gray-50 dark:bg-black/20 rounded-lg p-4">
            <h3 className="text-lg font-semibold dark:text-white mb-2">
              Key Assumptions
            </h3>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-4 text-sm">
              <div>
                <span className="font-medium dark:text-gray-300">
                  Initial FCF:
                </span>
                <span className="ml-2 dark:text-white">
                  ₹{formData.initialFCF} Cr
                </span>
              </div>
              <div>
                <span className="font-medium dark:text-gray-300">
                  Growth Rate:
                </span>
                <span className="ml-2 dark:text-white">
                  {formData.growthRate}%
                </span>
              </div>
              <div>
                <span className="font-medium dark:text-gray-300">
                  Terminal Growth:
                </span>
                <span className="ml-2 dark:text-white">
                  {formData.terminalGrowthRate}%
                </span>
              </div>
              <div>
                <span className="font-medium dark:text-gray-300">
                  Discount Rate:
                </span>
                <span className="ml-2 dark:text-white">
                  {formData.discountRate}%
                </span>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default DCF;
